google_analytics_key: null
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
title: HENERAL LUMA handcrafted leathergoods
url: https://heneralluma.store/
logo: /images/icon.jpg
author:
  name: heneral
  email: henerallumaleathergoods@gmail.com
  phone: "+639272236557"
  facebook: https://www.facebook.com/HDLEATHERPH/
  instagram: https://www.instagram.com/heneral.luma_leathercraft/
social_icons:
  - Email
  - Facebook
  - Instagram
permalink: pretty
social:
  - name: Facebook
    links:
      - https://www.facebook.com/HDLEATHERPH/
  - name: Instagram
    links:
      - https://www.instagram.com/heneral.luma_leathercraft/
defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: index.html
    values:
      layout: default
collections:
  staff_members:
    output: false
  products:
    output: true
jekyll-archives:
  enabled:
    - categories
timezone: Etc/UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
baseurl: ""
description: Handcrafted Leathergoods
