backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: products
    label: Products
    label_singular: Product
    folder: _products
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description_markdown", widget: "markdown" }
      - { label: "Leather Type", name: "leather_type", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Stock", name: "stock", widget: "number" }
      - label: "Sizes"
        name: "sizes"
        widget: "list"
        field:
          { label: "Size", name: "", widget: "string" }
      - label: "Styles"
        name: "styles"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Color", name: "color", widget: "color" }
          - { label: "Image", name: "image", widget: "image" }
  - name: pages
    label: Pages
    label_singular: Page
    create: true
    folder: /
    slug: "{{slug}}"
    format: html
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body_markdown", widget: "markdown" }
  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "Config"
        name: "config"
        file: "_config.yml"
        editor:
          preview: false
        fields:
          # ---- Site ----
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Base URL", name: "baseurl", widget: "string", required: false }
          - { label: "Google Analytics Key", name: "google_analytics_key", widget: "string", required: false }
          - { label: "Google Maps API Key", name: "google_maps_javascript_api_key", widget: "string", required: false }
          - { label: "Snipcart Key", name: "snipcart_key", widget: "string", required: false }
          - { label: "Snipcart Currency", name: "snipcart_currency", widget: "string", required: false }

          # SEO / Branding
          - { label: "Logo Path", name: "logo", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

          # Author Info
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
              - { label: "Twitter", name: "twitter", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }

          # Social Links
          - label: "Social"
            name: "social"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                field: { label: "URL", name: "url", widget: "string" }

          # Social Icons
          - label: "Social Icons"
            name: "social_icons"
            widget: "list"
            field: { label: "Icon Name", name: "icon", widget: "string" }