backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: products
    label: Products
    label_singular: Product
    folder: _products
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description_markdown", widget: "markdown" }
      - { label: "Leather Type", name: "leather_type", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Stock", name: "stock", widget: "number" }
      - label: "Sizes"
        name: "sizes"
        widget: "list"
        field:
          { label: "Size", name: "", widget: "string" }
      - label: "Styles"
        name: "styles"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Color", name: "color", widget: "color" }
          - { label: "Image", name: "image", widget: "image" }
  - name: pages
    label: Pages
    label_singular: Page
    create: true
    slug: "{{slug}}"
    format: yaml
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body_markdown", widget: "markdown" }
