backend:
  name: git-gateway
  branch: main

media_folder: "images"     # where uploaded files go in the repo
public_folder: "/images"   # how they’re referenced in the site

collections:
  # --- Site Settings: edit _config.yml ---
  - name: settings
    label: "Site Settings"
    editor:
      preview: false
    delete: false
    files:
      - label: "Jekyll Config"
        name: "jekyll_config"
        file: "_config.yml"
        format: "yml"
        fields:
          
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Base URL", name: "baseurl", widget: "string", required: false }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Description", name: "description", widget: "string" }
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string", required: false }
              - { label: "Phone", name: "phone", widget: "string", required: false }
              - { label: "Facebook", name: "facebook", widget: "string", required: false }
              - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - label: "Social"
            name: "social"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: "Links"
                name: "links"
                widget: "list"
                field: { label: "Link", name: "link", widget: "string" }
          - label: "Social Icons"
            name: "social_icons"
            widget: "list"
            field: { label: "Icon", name: "icon", widget: "string" }
          
         

  # --- Products content ---
  - name: products
    label: Products
    label_singular: Product
    folder: _products
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    extension: "md"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Leather Type", name: "leather_type", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string", required: false }
      - { label: "Stock", name: "stock", widget: "number", required: false }
      - label: "Sizes"
        name: "sizes"
        widget: "list"
        field:
          { label: "Size", name: "size", widget: "string" }
      - label: "Styles"
        name: "styles"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Color", name: "color", widget: "color" }
          - { label: "Image", name: "image", widget: "image" }
