backend:
  name: github
  repo: your-username/your-repo
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: products
    label: Products
    label_singular: Product
    folder: _products
    create: true
    slug: "{{slug}}"
    format: yaml
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description_markdown", widget: "markdown" }
      - { label: "Garment Type", name: "garment_type", widget: "string", required: false }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "SKU", name: "sku", widget: "string" }
      - { label: "Stock", name: "stock", widget: "number" }
      - label: "Sizes"
        name: "sizes"
        widget: "list"
        field:
          { label: "Size", name: "", widget: "string" }
      - label: "Styles"
        name: "styles"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Color", name: "color", widget: "color" }
          - { label: "Image", name: "image", widget: "image" }
